export enum Actions {
  Manage = 'manage',
  Create = 'create',
  Read = 'read',
  Update = 'update',
  Delete = 'delete',
  Register = 'register',
  ReadProfile = 'read-profile',
  ChangeStatus = 'change-status',
  toInvoice = 'to-invoice',
  Download = 'download',
  Import = 'import',
  RecoveryId = 'recovery-id',
  ForceSync = 'force-sync',
  View = 'view',
  Transfer = 'transfer',
  Allocate = 'allocate',
  Return = 'return',
  Block = 'Block',
  Unblock = 'Unblock',
  Process = 'Process',
  Reprocess = 'Reprocess',
}

export enum Subjects {
  User = 'User',
  Product = 'Product',
  Truckload = 'Truckload',
  Losses = 'Losses',
  DescriptionLosses = 'DescriptionLosses',
  All = 'all',
  Logix = 'Logix',
  Lobby = 'Lobby',
  MobileLobby = 'MobileLobby',
  Logistics = 'Logistics',
  Protheus = 'Protheus',
  GupyEmployee = 'GupyEmployee',
  ModuleRh = 'ModuleRh',
  LogisticsLoads = 'LogisticsLoads',
  Patrimonny = 'Patrimonny',
  FinancialCustomers = 'FinancialCustomers',
  LogisticsDares = 'LogisticsDares',
}